package com.musicplayer.services;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Carga estática de los archivos de configuración de la aplicación.
 *
 * <p>Gestiona dos fuentes de propiedades:
 * <ul>
 *   <li>{@code config.properties} — configuración de usuario (clave API, etc.).
 *       Su ausencia lanza {@link ExceptionInInitializerError}.</li>
 *   <li>{@code app.properties} — metadatos generados por Maven en tiempo de build
 *       (versión). Su ausencia se tolera silenciosamente para no romper el
 *       entorno de desarrollo antes del primer {@code mvn compile}.</li>
 * </ul>
 */
public class ConfigLoader {

    private static final Properties props    = new Properties();
    private static final Properties appProps = new Properties();

    static {
        try (InputStream in = ConfigLoader.class.getResourceAsStream(
                "/com/musicplayer/config.properties")) {
            if (in != null) props.load(in);
        } catch (IOException e) {
            throw new ExceptionInInitializerError("Cannot load config.properties: " + e.getMessage());
        }
        // app.properties is generated by Maven filtering; absent before first build — fail silently
        try (InputStream in = ConfigLoader.class.getResourceAsStream(
                "/com/musicplayer/app.properties")) {
            if (in != null) appProps.load(in);
        } catch (IOException ignored) {}
    }

    public static String get(String key) {
        return props.getProperty(key);
    }

    public static int getInt(String key, int defaultValue) {
        String val = props.getProperty(key);
        if (val == null) return defaultValue;
        try { return Integer.parseInt(val.trim()); }
        catch (NumberFormatException e) { return defaultValue; }
    }

    /** Returns the app version from app.properties, or empty string if unavailable. */
    public static String getVersion() {
        return appProps.getProperty("version", "");
    }
}